# Generated by Django 4.2.20 on 2025-03-20 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': [('can_add', 'Can Add Book'), ('can_update_book', 'Can Update Book')]},
        ),
    ]
